extends: 'eslint:recommended'
env:
  browser: true
  es6: true
parserOptions:
  sourceType: module
rules:
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
